#!/usr/bin/env python3
"""Generate (and drift-check) the canonical provider-neutral catalog.

The catalog is the single canonical description of every skill, agent, and
entrypoint (slash command) the platform agent-kit ships — the source the
provider adapter packs (Claude/Codex/OpenCode) and the root-contract generator
(E5) render from. It is GENERATED from frontmatter (the sole authoring surface),
mirroring the M1 `data/facts/environment-map.json` pattern — never hand-edited.

Schema is FROZEN as of provider-neutral-agent-kit-m3 (S3.1). Each entry:
  id            "<kind>/<name>" — stable per (kind, filename/name)
  kind          "skill" | "agent" | "entrypoint"
  name          frontmatter name (skills/agents) or filename stem (commands)
  description   frontmatter description
  owner         frontmatter `owner:` or default "platform-tooling"
  domain        frontmatter `domain:` or the name's first hyphen-segment
  provenance    repo-relative source path
  freshness     last-commit AUTHOR date (git %aI — rebase-stable; never %cI) or
                mtime fallback — informational, EXCLUDED from the --check drift
                comparison (it would churn every commit); present so E5/E6 can
                surface staleness on demand.
  sensitivity   "shared-safe" (default) | "private-local" — the only real trust
                split today (M2's memoryVisible gate); every catalog entry is
                shared-safe (the private-local memory tier is not cataloged).
  ioSchema      skills: allowed-tools list; agents: tools list; commands:
                argument-hint string (the shapes that exist today — not a
                speculative JSON Schema).
  modelClass    agents' `model-class` (never raw `model:`); null for skills/commands.
  providerSupport
                per-provider `native|adapted|degraded`. A Codex entrypoint may
                name a reviewed skill adapter in frontmatter; other Claude-only
                orchestration remains degraded rather than silently dropped.
  providerPartial / degradationNote
                compatibility summary derived from providerSupport.

An entry whose frontmatter carries `catalog-exclude: true` is omitted entirely
(the `-deep` model-tier agent variants generated by mode-variant-agents.py — they
are Claude-Workflow dispatch targets, not distinct capabilities).

Stdlib + PyYAML (installed in the data-lint image). CWD-independent.

Usage:
  catalog-generate.py            regenerate data/facts/catalog.json
  catalog-generate.py --check    drift + coverage gate (exit 0 clean | 2 drift | 3 coverage)
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

# Top-level `key: value` on one line — a SAFETY-NET fallback for frontmatter that
# isn't strict-YAML-valid (e.g. an unquoted `: ` colon-space in a description).
# CI Gate 2 now strict-validates all three content tiers, so the corpus is clean;
# this fallback only matters if an invalid file slips in before the gate runs
# (the MCP server's own gray-matter loader would silently DROP such a file, so
# the catalog must not silently drop it either).
_SCALAR_LINE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):\s?(.*)$")

ROOT = Path(__file__).resolve().parents[2]  # data/scripts/x.py -> repo root
SKILLS_DIR = ROOT / "data" / "skills"
AGENTS_DIR = ROOT / "data" / "agents"
COMMANDS_DIR = ROOT / "data" / "commands"
CATALOG_PATH = ROOT / "data" / "facts" / "catalog.json"

# Claude-Code-only capabilities: an entry needing any is provider-partial. The
# Agent tool (subagent dispatch) + AskUserQuestion (elicitation) + the background
# Workflow tool are Claude-Code constructs with no Codex/OpenCode equivalent.
CLAUDE_ONLY_TOOLS = {"Agent", "AskUserQuestion", "Workflow", "Task"}

# Entrypoint (slash-command) orchestration markers: Gen-2 pipelines drive the
# background Workflow tool; Gen-1 pipelines dispatch subagents via the Agent tool.
_WORKFLOW_RE = re.compile(r"Workflow\(|[A-Za-z0-9-]+-workflow\.mjs")
_AGENT_DISPATCH_RE = re.compile(r"sub-?agent|subagent_type|Agent tool", re.IGNORECASE)

SCHEMA_VERSION = "1.1"


def _frontmatter(text: str) -> tuple[dict, str]:
    """Split a markdown file into (frontmatter dict, body). Tolerant of files
    with no frontmatter (returns {}, whole text)."""
    if not text.startswith("---"):
        return {}, text
    # Line-anchored close: a `---` inside a frontmatter value (e.g. a markdown
    # rule) must not truncate the block the way a plain str.split would.
    sections = re.split(r"(?m)^---[ \t]*$", text, maxsplit=2)
    if len(sections) < 3:
        return {}, text
    raw_fm, body = sections[1], sections[2]
    try:
        fm = yaml.safe_load(raw_fm)
        if isinstance(fm, dict):
            return fm, body
    except yaml.YAMLError:
        pass
    # Lenient fallback: extract flat top-level scalar/list keys line-by-line so a
    # single unquoted colon-space in a description doesn't drop the whole entry.
    fm = {}
    for line in raw_fm.splitlines():
        if not line or line[0] in " \t-#":  # skip indented/list/comment lines
            continue
        m = _SCALAR_LINE.match(line)
        if m:
            key, val = m.group(1), m.group(2).strip()
            # Strip one matching pair of surrounding quotes.
            if len(val) >= 2 and val[0] in "\"'" and val[-1] == val[0]:
                val = val[1:-1]
            fm.setdefault(key, val)
    return fm, body


def _tool_list(value) -> list[str]:
    """Normalize a frontmatter tools value (comma string or YAML list) to a list."""
    if value is None:
        return []
    if isinstance(value, list):
        return [str(t).strip() for t in value if str(t).strip()]
    return [t.strip() for t in str(value).split(",") if t.strip()]


def _freshness(rel_path: str) -> str:
    """Last-commit AUTHOR date for the path; '' when unavailable (new/uncommitted).

    Deliberately %aI (author date), NOT %cI (committer date): a rebase rewrites
    every committer date it touches, so %cI made this field a function of WHEN
    history was last replayed rather than when the content actually changed. That
    is how main came to carry 140/157 entries stamped with one rebase-era
    timestamp (fixed in 45f1123). Author date survives rebase/cherry-pick, so a
    regen on a replayed branch still agrees with the branch it lands on.
    """
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%aI", "--", rel_path],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    try:
        # mtime fallback (ISO-8601 UTC, matching the git %aI shape) for
        # uncommitted entries — never a bare epoch integer. NOTE the UTC +00:00
        # offset is the tell that distinguishes a fallback value from a real
        # git-derived one (which carries a local offset) when triaging.
        mtime = (ROOT / rel_path).stat().st_mtime
        return datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat()
    except OSError:
        return ""


def _domain(name: str, fm: dict) -> str:
    if fm.get("domain"):
        return str(fm["domain"])
    return name.split("-")[0] if "-" in name else (name or "general")


def _provider_partial(
    kind: str, fm: dict, tools: list[str], body: str
) -> tuple[bool, str | None]:
    # An explicit `provider-partial:` frontmatter bool is authoritative.
    override = fm.get("provider-partial")
    if isinstance(override, bool):
        if override:
            return True, str(fm.get("degradation-note") or "Marked provider-partial by frontmatter.")
        return False, None

    reasons = set(tools) & CLAUDE_ONLY_TOOLS
    if "AskUserQuestion" in body:
        reasons.add("AskUserQuestion")
    if kind == "entrypoint":
        # Slash-command orchestrators depend on Claude-Code-only orchestration.
        if _WORKFLOW_RE.search(body):
            reasons.add("Workflow")
        if _AGENT_DISPATCH_RE.search(body):
            reasons.add("Agent")
    if not reasons:
        return False, None
    note = (
        f"Uses Claude-only capability: {', '.join(sorted(reasons))}. "
        "Providers without an explicit reviewed adapter render this degraded."
    )
    return True, note


def _provider_support(kind: str, fm: dict, partial: bool) -> dict[str, str]:
    """Provider-specific support. Claude is the canonical source runtime.

    Codex entrypoints are opt-in because translating orchestration mechanically
    would create false capability claims. `codex-adapter: skill` means a
    provider-reviewed source exists under data/provider-adapters/codex/.
    `codex-adapter: prompt-policy` on an agent records that Claude tool
    restrictions were translated as instructions, not runtime enforcement.
    """
    codex_adapted = (
        (kind == "entrypoint" and fm.get("codex-adapter") == "skill")
        or (kind == "agent" and fm.get("codex-adapter") == "prompt-policy")
    )
    codex = "adapted" if codex_adapted else (
        "degraded" if partial else "native"
    )
    return {
        "claude": "native",
        "codex": codex,
        "opencode": "degraded" if partial else "native",
    }


def _entry(kind: str, name: str, fm: dict, body: str, rel_path: str) -> dict:
    tools = _tool_list(fm.get("allowed-tools") if kind == "skill" else fm.get("tools"))
    partial, note = _provider_partial(kind, fm, tools, body)
    support = _provider_support(kind, fm, partial)
    if kind == "skill":
        io_schema = {"tools": tools}
    elif kind == "agent":
        io_schema = {"tools": tools}
    else:  # entrypoint / command
        io_schema = {
            "argumentHint": str(fm.get("argument-hint", "")) or None,
            "codexAdapter": str(fm.get("codex-adapter", "")) or None,
        }
    return {
        "id": f"{kind}/{name}",
        "kind": kind,
        "name": name,
        "description": str(fm.get("description", "")).strip(),
        "owner": str(fm.get("owner", "platform-tooling")),
        "domain": _domain(name, fm),
        "provenance": rel_path,
        "freshness": _freshness(rel_path),
        "sensitivity": str(fm.get("sensitivity", "shared-safe")),
        "ioSchema": io_schema,
        "modelClass": (str(fm["model-class"]) if fm.get("model-class") else None),
        "providerSupport": support,
        "providerPartial": any(value == "degraded" for value in support.values()),
        "degradationNote": note,
    }


def _excluded(fm: dict) -> bool:
    """A `catalog-exclude: true` frontmatter flag keeps an entry OUT of the catalog
    (and therefore out of every generated provider pack). Used for the internal
    model-tier agent variants (mode-variant-agents.py's `-deep` files): they are
    dispatch targets for the Claude-Workflow runtime, not distinct capabilities, so
    the public catalog stays 40/97/16 and the Codex/OpenCode packs never render an
    agent whose only dispatcher is a Claude-Code-only construct they cannot run."""
    return fm.get("catalog-exclude") is True


def build_catalog() -> dict:
    entries: list[dict] = []

    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        fm, body = _frontmatter(skill_md.read_text(encoding="utf-8"))
        if _excluded(fm):
            continue
        name = str(fm.get("name") or skill_md.parent.name)
        rel = str(skill_md.relative_to(ROOT))
        entries.append(_entry("skill", name, fm, body, rel))

    for agent_md in sorted(AGENTS_DIR.glob("*.md")):
        fm, body = _frontmatter(agent_md.read_text(encoding="utf-8"))
        if _excluded(fm):
            continue
        name = str(fm.get("name") or agent_md.stem)
        rel = str(agent_md.relative_to(ROOT))
        entries.append(_entry("agent", name, fm, body, rel))

    for cmd_md in sorted(COMMANDS_DIR.glob("*.md")):
        fm, body = _frontmatter(cmd_md.read_text(encoding="utf-8"))
        if _excluded(fm):
            continue
        name = cmd_md.stem  # commands carry no `name:` — filename IS the /slash id
        rel = str(cmd_md.relative_to(ROOT))
        entries.append(_entry("entrypoint", name, fm, body, rel))

    entries.sort(key=lambda e: (e["kind"], e["name"]))
    counts = {
        "skills": sum(1 for e in entries if e["kind"] == "skill"),
        "agents": sum(1 for e in entries if e["kind"] == "agent"),
        "entrypoints": sum(1 for e in entries if e["kind"] == "entrypoint"),
    }
    return {
        "_comment": (
            "GENERATED by data/scripts/catalog-generate.py from frontmatter — do NOT "
            "hand-edit. Regenerate: python3 data/scripts/catalog-generate.py. "
            "Drift + coverage are gated in CI (data-lint) via --check."
        ),
        "_schemaVersion": SCHEMA_VERSION,
        "counts": counts,
        "entries": entries,
    }


def _strip_freshness(catalog: dict) -> dict:
    """Return a deep-ish copy with freshness removed — freshness is informational
    and git-derived, so it must not make the drift gate churn."""
    return {
        **catalog,
        "entries": [{k: v for k, v in e.items() if k != "freshness"} for e in catalog["entries"]],
    }


def _serialize(catalog: dict) -> str:
    return json.dumps(catalog, indent=2, ensure_ascii=False) + "\n"


def check() -> int:
    fresh = build_catalog()
    counts = fresh["counts"]
    failures: list[str] = []

    # Coverage: counts are derived from disk, never hardcoded.
    for kind, plural in (("skill", "skills"), ("agent", "agents"), ("entrypoint", "entrypoints")):
        for e in fresh["entries"]:
            if e["kind"] != kind:
                continue
            for field in ("id", "kind", "name", "description", "owner", "domain",
                          "provenance", "sensitivity"):
                if not e.get(field):
                    failures.append(f"{e['id']}: missing required field '{field}'")
        if counts[plural] == 0:
            failures.append(f"coverage: zero {plural} found (wrong CWD?)")

    # id uniqueness — a duplicated frontmatter `name:` would collide E5 consumers.
    seen: dict[str, int] = {}
    for e in fresh["entries"]:
        seen[e["id"]] = seen.get(e["id"], 0) + 1
    for cid, n in seen.items():
        if n > 1:
            failures.append(f"duplicate id '{cid}' ({n} entries)")

    # Sentinels — provider-partial detection must hold for the load-bearing cases:
    # orchestration entrypoints (Gen-1 dispatch / Gen-2 Workflow) are provider-partial;
    # a plain ops skill is not.
    by_id = {e["id"]: e for e in fresh["entries"]}
    for sid, want in (("entrypoint/milestone-pipeline", True),
                      ("skill/handoff", False)):
        e = by_id.get(sid)
        if e is None:
            failures.append(f"sentinel: {sid} absent from catalog")
        elif e["providerPartial"] is not want:
            failures.append(f"sentinel: {sid} providerPartial={e['providerPartial']}, want {want}")
    support_expectations = {
        "entrypoint/milestone-pipeline": {"claude": "native", "codex": "adapted", "opencode": "degraded"},
        "agent/milestone-closure-verifier": {"claude": "native", "codex": "adapted", "opencode": "native"},
        "agent/milestone-operations-adversary": {"claude": "native", "codex": "adapted", "opencode": "native"},
        "skill/handoff": {"claude": "native", "codex": "native", "opencode": "native"},
    }
    for sid, want in support_expectations.items():
        entry = by_id.get(sid)
        if entry is not None and entry.get("providerSupport") != want:
            failures.append(
                f"sentinel: {sid} providerSupport={entry.get('providerSupport')}, want {want}"
            )

    if failures:
        for f in failures:
            print(f"FAIL: {f}", file=sys.stderr)
        print(f"{len(failures)} coverage failure(s)", file=sys.stderr)
        return 3

    # Drift: on-disk catalog must match a fresh generation (excluding freshness).
    try:
        on_disk = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"FAIL: cannot read {CATALOG_PATH}: {exc} — run catalog-generate.py", file=sys.stderr)
        return 2
    if _strip_freshness(on_disk) != _strip_freshness(fresh):
        print(
            "FAIL: data/facts/catalog.json is stale — regenerate with "
            "`python3 data/scripts/catalog-generate.py`",
            file=sys.stderr,
        )
        return 2

    print(
        f"catalog: clean — {counts['skills']} skills, {counts['agents']} agents, "
        f"{counts['entrypoints']} entrypoints"
    )
    return 0


def self_test() -> int:
    """Exercise the parse fallback + provider-partial detection on torture inputs."""
    failures = []

    def eq(label, got, want):
        if got != want:
            failures.append(f"{label}: got {got!r}, want {want!r}")

    # strict-valid frontmatter parses via yaml
    fm, _ = _frontmatter('---\nname: a\ndescription: "x: y"\n---\nbody')
    eq("strict.desc", fm.get("description"), "x: y")
    # unquoted colon-space -> lenient fallback recovers the full line
    fm, _ = _frontmatter("---\nname: b\ndescription: Phase 2. Inputs: {X}. Done.\n---\nbody")
    eq("fallback.desc", fm.get("description"), "Phase 2. Inputs: {X}. Done.")
    # a `---` inside a value must not truncate the block (line-anchored split)
    fm, body = _frontmatter("---\nname: c\ndescription: has --- dash: inline\n---\nthe body")
    eq("dashinvalue.name", fm.get("name"), "c")
    eq("dashinvalue.body", body.strip(), "the body")
    # fallback strips one matching pair of surrounding quotes
    fm, _ = _frontmatter("---\nname: d\ndescription: 'q: v'\ndesc2: also: bad\n---\nb")
    eq("fallback.quotestrip", fm.get("description"), "q: v")

    # provider-partial: frontmatter override wins
    p, _ = _provider_partial("skill", {"provider-partial": True}, [], "")
    eq("override.true", p, True)
    p, _ = _provider_partial("skill", {"provider-partial": False}, ["Agent"], "AskUserQuestion")
    eq("override.false", p, False)
    # skill with a Claude-only tool
    p, _ = _provider_partial("skill", {}, ["Read", "Agent"], "")
    eq("skill.agent", p, True)
    # entrypoint that dispatches subagents / uses Workflow
    eq("entry.dispatch", _provider_partial("entrypoint", {}, [], "Use the milestone-researcher sub-agent.")[0], True)
    eq("entry.workflow", _provider_partial("entrypoint", {}, [], "runs a foo-workflow.mjs")[0], True)
    # a plain skill is not provider-partial
    eq("skill.plain", _provider_partial("skill", {}, ["Read", "Bash"], "no special tools")[0], False)
    eq(
        "entry.codex-adapted",
        _provider_support("entrypoint", {"codex-adapter": "skill"}, True),
        {"claude": "native", "codex": "adapted", "opencode": "degraded"},
    )
    eq(
        "agent.codex-prompt-policy",
        _provider_support("agent", {"codex-adapter": "prompt-policy"}, False),
        {"claude": "native", "codex": "adapted", "opencode": "native"},
    )

    for f in failures:
        print(f"FAIL: {f}", file=sys.stderr)
    if failures:
        print(f"{len(failures)} self-test failure(s)", file=sys.stderr)
        return 1
    print("catalog-generate self-test: OK")
    return 0


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return self_test()
    if "--check" in argv:
        return check()
    catalog = build_catalog()
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(_serialize(catalog), encoding="utf-8")
    c = catalog["counts"]
    print(
        f"wrote {CATALOG_PATH.relative_to(ROOT)} — {c['skills']} skills, "
        f"{c['agents']} agents, {c['entrypoints']} entrypoints, "
        f"{sum(1 for e in catalog['entries'] if e['providerPartial'])} provider-partial"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
