#!/usr/bin/env python3
"""Generate (and drift-check) the `--mode deep` model-tier agent variants.

Four Gen-2 discovery pipelines bump ONE scout up a model tier when run with
`--mode deep` (capability-scout -> internal-adversary, mesh-as-code ->
cartographer, interop-discovery -> interop-cartographer, frontend-uplift ->
current-state-critic). The old code did this with a hardcoded `model: 'opus'`
literal inside the `*-workflow.mjs` — but the Workflow runtime has NO filesystem
access, so it cannot resolve `model-policy.json` at runtime; a raw alias in the
`.mjs` was the only lever, and it went stale the moment the fleet re-pointed
(the deep tier is `fable` now, not `opus`).

The fix (S3.8b): the deep tier lives in a dedicated per-mode AGENT FILE
(`<base>-deep.md`, model-class `deep-reasoning-high`, stamped by
model-policy-apply.py), and the `.mjs` dispatches `agentType: '<base>-deep'` in
deep mode — a plain string, zero model literal, zero fs access.

These variant files are GENERATED here (never hand-edited) so their body stays
byte-identical to the base agent's — a hand-copy would drift. They carry
`catalog-exclude: true` so they never inflate the public catalog or the
Codex/OpenCode packs (those providers cannot run the Claude-Workflow that
dispatches them). model-policy-apply.py still owns their `model-class`/`model`/
`effort` keys and requires an assignment for each (see data/model-policy.json).

Stdlib only. CWD-independent.

Modes:
  mode-variant-agents.py            (default) regenerate the variant files
  mode-variant-agents.py --apply    same as default (explicit)
  mode-variant-agents.py --check    drift gate: exit 0 clean | 1 drift/missing
  mode-variant-agents.py --self-test
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # data/scripts/x.py -> repo root
AGENTS_DIR = ROOT / "data" / "agents"

# base agent name -> the pipeline that dispatches its deep variant (for the
# provenance comment). Every variant resolves to model-class deep-reasoning-high
# via its data/model-policy.json assignment (added in the same S3.8b commit).
VARIANTS = {
    "capability-scout-internal-adversary": "capability-scout-workflow.mjs",
    "mesh-as-code-cartographer": "mesh-as-code-workflow.mjs",
    "interop-discovery-interop-cartographer": "interop-discovery-workflow.mjs",
    "frontend-uplift-current-state-critic": "frontend-uplift-workflow.mjs",
}

# Frontmatter keys model-policy-apply.py owns — excluded from the base->variant
# copy (the variant gets its own, stamped from its deep-reasoning-high assignment)
# and stripped from the on-disk variant before the drift compare.
MODEL_OWNED = ("model-class", "model", "effort")


def _split(text: str) -> tuple[list[str], str]:
    """Return (frontmatter_lines, body) for a `---\\n...\\n---\\nbody` file.
    frontmatter_lines are the lines BETWEEN the fences (no fences)."""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise ValueError("no frontmatter opener")
    try:
        close = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        raise ValueError("unterminated frontmatter")
    fm = lines[1:close]
    body = "".join(lines[close + 1:])
    return fm, body


def _key(line: str) -> str:
    """Top-level YAML key of a frontmatter line, or '' for indented/list/comment."""
    if not line or line[0] in (" ", "\t", "-", "#") or ":" not in line:
        return ""
    return line.split(":", 1)[0].strip()


def render_variant(base_name: str, pipeline: str, base_text: str) -> str:
    """Base agent text -> its `-deep` variant text (model keys omitted — they are
    stamped by model-policy-apply.py). Pure; covered by --self-test."""
    fm, body = _split(base_text)
    variant = base_name + "-deep"
    comment = [
        f"# GENERATED by data/scripts/mode-variant-agents.py from {base_name}.md — do NOT hand-edit.\n",
        f"# --mode deep model-tier variant (model-class deep-reasoning-high), dispatched only by\n",
        f"# {pipeline}. Body is kept byte-identical to the base by mode-variant-agents.py --check.\n",
    ]
    out_fm: list[str] = []
    for ln in fm:
        k = _key(ln)
        if k in MODEL_OWNED:
            continue  # stamped by model-policy-apply.py from the deep assignment
        if k == "name":
            out_fm.append(f"name: {variant}\n")
            continue
        out_fm.append(ln)
    # Ensure catalog-exclude is present exactly once, at the end of the block.
    out_fm = [ln for ln in out_fm if _key(ln) != "catalog-exclude"]
    if out_fm and not out_fm[-1].endswith("\n"):
        out_fm[-1] += "\n"
    out_fm.append("catalog-exclude: true\n")
    return "---\n" + "".join(comment + out_fm) + "---\n" + body


def _strip_model_keys(text: str) -> str:
    """Drop the model-policy-owned frontmatter lines so an on-disk (stamped)
    variant compares equal to a freshly-rendered (unstamped) one."""
    fm, body = _split(text)
    kept = [ln for ln in fm if _key(ln) not in MODEL_OWNED]
    return "---\n" + "".join(kept) + "---\n" + body


def _targets() -> list[tuple[str, str, Path, Path]]:
    out = []
    for base_name, pipeline in VARIANTS.items():
        base = AGENTS_DIR / f"{base_name}.md"
        variant = AGENTS_DIR / f"{base_name}-deep.md"
        out.append((base_name, pipeline, base, variant))
    return out


def apply() -> int:
    wrote = 0
    for base_name, pipeline, base, variant in _targets():
        if not base.is_file():
            print(f"FAIL: base agent missing: {base.relative_to(ROOT)}", file=sys.stderr)
            return 1
        rendered = render_variant(base_name, pipeline, base.read_text(encoding="utf-8"))
        variant.write_text(rendered, encoding="utf-8")
        wrote += 1
    print(f"mode-variant-agents: wrote {wrote} deep variant(s) "
          "(model keys pending model-policy-apply.py stamp)")
    return 0


def check() -> int:
    problems: list[str] = []
    for base_name, pipeline, base, variant in _targets():
        if not base.is_file():
            problems.append(f"base agent missing: {base.relative_to(ROOT)}")
            continue
        if not variant.is_file():
            problems.append(f"variant missing: {variant.relative_to(ROOT)} — run mode-variant-agents.py --apply")
            continue
        want = render_variant(base_name, pipeline, base.read_text(encoding="utf-8"))
        have = _strip_model_keys(variant.read_text(encoding="utf-8"))
        if want != have:
            problems.append(
                f"{variant.relative_to(ROOT)} drifted from {base.name} "
                "(base body/frontmatter changed?) — run mode-variant-agents.py --apply, "
                "then model-policy-apply.py"
            )
    for p in problems:
        print(f"FAIL: {p}", file=sys.stderr)
    if problems:
        print(f"{len(problems)} mode-variant drift(s)", file=sys.stderr)
        return 1
    print(f"mode-variant-agents: {len(VARIANTS)} deep variant(s) in sync with their base agents")
    return 0


def self_test() -> int:
    failures = []
    base = (
        "---\n"
        "name: demo-scout\n"
        'description: "A scout. Uses: X."\n'
        "tools: Read, Grep\n"
        "model-class: balanced-high\n"
        "model: sonnet\n"
        "effort: high\n"
        "memory: project\n"
        "type: agent\n"
        "status: active\n"
        "tags:\n"
        "  - type/agent\n"
        "---\n"
        "# Demo Scout\n\nBody line with `.claude/references/x.md`.\n"
    )
    r = render_variant("demo-scout", "demo-workflow.mjs", base)

    def ck(label, cond):
        if not cond:
            failures.append(label)

    ck("name overridden", "name: demo-scout-deep\n" in r)
    ck("model keys dropped", "model-class:" not in r and "\nmodel:" not in r and "effort:" not in r)
    ck("catalog-exclude added once", r.count("catalog-exclude: true") == 1)
    ck("description preserved verbatim", 'description: "A scout. Uses: X."\n' in r)
    ck("tools preserved", "tools: Read, Grep\n" in r)
    ck("body byte-identical", r.endswith("# Demo Scout\n\nBody line with `.claude/references/x.md`.\n"))
    ck("provenance comment present", "GENERATED by data/scripts/mode-variant-agents.py" in r)
    ck("tags list preserved", "  - type/agent\n" in r)

    # round-trip: stamping model keys then stripping them reproduces render output
    stamped = r.replace(
        "tools: Read, Grep\n",
        "tools: Read, Grep\nmodel-class: deep-reasoning-high\nmodel: fable\neffort: high\n",
    )
    ck("strip-model round-trips", _strip_model_keys(stamped) == r)

    for f in failures:
        print(f"FAIL: {f}", file=sys.stderr)
    if failures:
        print(f"{len(failures)} self-test failure(s)", file=sys.stderr)
        return 1
    print("mode-variant-agents self-test: OK")
    return 0


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return self_test()
    if "--check" in argv:
        return check()
    return apply()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
