from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPT_DIR))

import obsidian_vault_validate as validator  # noqa: E402


class ObsidianVaultValidatorTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        self.workspace = self.root / "workspace"
        self.vault = self.root / "Presentation"
        self.workspace.mkdir()
        self.vault.mkdir()
        (self.workspace / "scripts").mkdir()

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def write(self, root: Path, relative: str, content: str) -> Path:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def manifest(self, project_id: str = "alpha") -> Path:
        payload = {
            "vault_root": str(self.workspace),
            "projects_root": "Notes/Projects",
            "projects": {
                "Alpha": {
                    "project_id": project_id,
                    "slugs": ["legacy-alpha"],
                }
            },
        }
        path = self.workspace / "scripts" / "project-map.json"
        path.write_text(json.dumps(payload), encoding="utf-8")
        return path

    def healthy_fixture(self) -> Path:
        manifest = self.manifest()
        self.write(self.vault, "Notes/Artifacts/alpha-roadmap.md", "# Roadmap\n")
        self.write(
            self.vault,
            "Notes/Projects/Alpha/_index.md",
            """---
type: project-hub
project: alpha
tags:
  - type/project-hub
  - project/alpha
---
# Alpha — project hub

> **Auto-generated by `scripts/project-linker.py` — do not edit by hand.**

[roadmap](../../Artifacts/alpha-roadmap.md)
![[Alpha-roadmaps.excalidraw]]
""",
        )
        self.write(
            self.vault,
            "Notes/Projects/Alpha/Alpha-roadmaps.excalidraw.md",
            """---
tags: [excalidraw, type/roadmap-status]
---
# Excalidraw Data

## Drawing
```json
{"type":"excalidraw","source":"workspace-roadmap-status","elements":[{"id":"a","type":"rectangle","link":"obsidian://open?vault=Presentation&file=Notes%2FArtifacts%2Falpha-roadmap.md","isDeleted":false}]}
```
""",
        )
        self.write(
            self.vault,
            "Notes/Canvases/alpha.canvas",
            json.dumps(
                {
                    "nodes": [
                        {
                            "id": "n1",
                            "type": "file",
                            "file": "Notes/Artifacts/alpha-roadmap.md",
                        }
                    ],
                    "edges": [],
                }
            ),
        )
        return manifest

    def test_clean_fixture_passes_every_check(self) -> None:
        manifest = self.healthy_fixture()
        report = validator.validate(self.vault, self.workspace, manifest)
        self.assertEqual(report.error_count, 0, report.as_dict())
        self.assertEqual(report.warning_count, 0, report.as_dict())
        self.assertGreater(report.checks["hub_links"].inspected, 0)
        self.assertGreater(report.checks["canvas_nodes"].inspected, 0)
        self.assertGreater(report.checks["excalidraw_links"].inspected, 0)

    def test_contract_violations_have_stable_codes(self) -> None:
        manifest = self.manifest()
        source = self.write(self.workspace, "source/shared.md", "# Shared\n")
        alias_a = self.vault / "AgentDocs/source/shared.md"
        alias_b = self.vault / "Notes/Projects/Alpha/_sources/shared.md"
        alias_a.parent.mkdir(parents=True)
        alias_b.parent.mkdir(parents=True)
        os.symlink(source, alias_a)
        os.symlink(source, alias_b)
        self.write(
            self.vault,
            "Notes/Projects/Alpha/_index.md",
            """---
type: project-hub
project: wrong
tags: [type/project-hub, project/wrong]
---
# Alpha — project hub
> **Auto-generated by `scripts/project-linker.py` — do not edit by hand.**
[missing](../../../plans/missing.md)
![[Alpha-roadmaps.excalidraw]]
""",
        )
        self.write(
            self.vault,
            "Notes/Projects/Alpha/Alpha-roadmaps.excalidraw.md",
            """---
tags: [excalidraw, type/roadmap-status]
---
## Drawing
```json
{"type":"excalidraw","source":"workspace-roadmap-status","elements":[{"id":"a","type":"rectangle","link":"obsidian://open?path=%2FUsers%2Fsomeone%2Fworkspace%2Froadmap.md","isDeleted":false}]}
```
""",
        )
        self.write(
            self.vault,
            "Notes/Canvases/alpha.canvas",
            json.dumps({"nodes": [{"id": "n1", "type": "file", "file": "plans/missing.md"}]}),
        )

        report = validator.validate(self.vault, self.workspace, manifest)
        codes = {finding.code for finding in report.findings}
        self.assertIn("PROJECT_HUB_METADATA_MISMATCH", codes)
        self.assertIn("PROJECT_HUB_TAG_MISMATCH", codes)
        self.assertIn("HUB_LINK_UNRESOLVED", codes)
        self.assertIn("CANVAS_FILE_UNRESOLVED", codes)
        self.assertIn("EXCALIDRAW_ABSOLUTE_PATH_URI", codes)
        self.assertIn("DUPLICATE_MARKDOWN_ALIAS", codes)

    def test_link_resolution_is_lexical_across_directory_symlink(self) -> None:
        source_notes = self.workspace / "Notes"
        source_notes.mkdir()
        self.write(self.workspace, "plans/exists-only-in-workspace.md", "# Hidden\n")
        hub = self.write(
            source_notes,
            "Projects/Alpha/_index.md",
            "[looks-valid-to-posix](../../../plans/exists-only-in-workspace.md)\n",
        )
        os.symlink(source_notes, self.vault / "Notes")

        index = validator.VaultIndex(self.vault)
        self.assertIn("Notes/Projects/Alpha/_index.md", index.files)
        resolved, error = index.resolve_link(
            "Notes/Projects/Alpha/_index.md",
            "../../../plans/exists-only-in-workspace.md",
        )
        self.assertIsNone(resolved)
        self.assertIn("absent", error or "")
        self.assertTrue(hub.exists())

    def test_json_report_order_is_deterministic(self) -> None:
        manifest = self.healthy_fixture()
        first = validator.validate(self.vault, self.workspace, manifest).as_dict()
        second = validator.validate(self.vault, self.workspace, manifest).as_dict()
        self.assertEqual(first, second)

    def test_compressed_excalidraw_uses_element_links_projection(self) -> None:
        drawing = validator.parse_excalidraw(
            """# Excalidraw Data

## Element Links
card-a: obsidian://open?vault=Presentation&file=Notes%2FArtifacts%2Falpha-roadmap.md

%%
## Drawing
```compressed-json
N4KAkARALgngDg
```
%%
"""
        )
        self.assertTrue(drawing["compressed"])
        self.assertEqual(drawing["elements"][0]["id"], "card-a")
        self.assertIn("alpha-roadmap.md", drawing["elements"][0]["link"])


if __name__ == "__main__":
    unittest.main()
